---

- name: Test if folder exist
  stat:
    path={{ phpstorm_dir }}
  register: phpstorm_exist

- name: Download phpStorm archive
  get_url:
    url=http://download.jetbrains.com/webide/PhpStorm-{{ phpstorm_version }}.tar.gz
    dest={{ phpstorm_archive }}
  when: phpstorm_exist.stat.exists == False

- name: Decompress phpStorm archive
  unarchive:
    src={{ phpstorm_archive }}
    dest={{ phpstorm_install_dir }}
    copy=no
  when: phpstorm_exist.stat.exists == False

- name: Move phpStorm folder
  shell:
    mv {{ phpstorm_install_dir }}/PhpStorm-* {{ phpstorm_dir }}
    creates="{{ phpstorm_dir }}"

- name: Create dir symlink
  file:
    src={{ phpstorm_dir }}
    dest={{ phpstorm_symlink_dir }}
    state=link

- name: Create bin symlink
  file:
    src={{ phpstorm_dir }}/bin/phpstorm.sh
    dest={{ phpstorm_bin }}
    state=link

- name: Remove phpStorm archive
  file:
    path={{ phpstorm_archive }}
    state=absent
